### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by czotti** [GuillaumeTh/dmriqcpy#17]
It could be very nice to have a more powerful searching function (maybe enable regex?).

Now you could search for only one term, let's says only `Pass` images, but you can't choose two or more status like: `[Pass|Warning]`.

Is it possible to have a columns search instead of a full search? to have more granularity in our export ?

**Comment by GuillaumeTh** [comment]
Good idea. I will test (or if you want you can) to add the regex search function https://datatables.net/reference/option/search.regex
